### ISSUE TITLE
class 'Sarav\Multiauth\Guard' does not have a method 'guard'

### ISSUE THREAD

**Issue by raghavendra89** [Sarav-S/Laravel-Multiauth#10]
Hi Sarav,

I'm trying to get this multiauth working. I've followed the instructions in your article. But when I try to access \user\login I'm getting this error.

ErrorException in Manager.php line 197:
call_user_func_array() expects parameter 1 to be a valid callback, class 'Sarav\Multiauth\Guard' does not have a method 'guard'

Can you please help me resolve this?

Thanks,

**Comment by Sarav-S** [comment]
Hi raghavendra,

I have written a sample code here https://github.com/Sarav-S/Laravel-Multiauth-SampleCode. Please check it and let me know if the issue still persists.

Sarav
