### ISSUE TITLE
can method for permissions return true to anything

### ISSUE THREAD

**Issue by arturcesarmelo** [Sarav-S/Laravel-Multiauth#16]
Hi, Sarav.

I've decide to use multi authentication for laravel 5.1 in a project for basic reasons. But i'm facing a problem with @can blade directive. Virtually, this directive returns **true** to anything, which did not precede before using the basic auth native from Laravel 5.1. The user has a Role relationship which returns a collections of Permissions contains the following attributes:

 - id;
 - name;
 - label;

the **label** attribute is the string with the permission name in snaked case.

I can not resolve this using a new implementation for check permissions because i'm talking about a project in advanced production stage. I hope it's a problem with how i implemented the Multi Auth, maybe i miss something on tutorial... could you help me?

**Comment by arturcesarmelo** [comment]
thanks to (DON'T) answer me.

**Comment by Sarav-S** [comment]
@arturcesarmelo I'm really sorry for replying late. Can you share me your blade code?

**Comment by Sarav-S** [comment]
Closing this issue since no reply received.
