### ISSUE TITLE
Compatible with L5.5?

### ISSUE THREAD

**Issue by neutt22** [Sarav-S/Laravel-Multiauth#17]
I was preparing for a small project and I'd like to know if this is compatible with current Laravel release version 5.5. Because in the Readme, it says its only for 5.1.*

**Comment by Sarav-S** [comment]
No it is not. Laravel 5.5 comes with inbuilt multiple authentication.

**Comment by neutt22** [comment]
@Sarav-S can you point me to the official doc where I could find the multiple authentication for 5.5?
