### ISSUE TITLE
Ploblem Class 'Illuminate\Auth\Guard' not found

### ISSUE THREAD

**Issue by Benjamin-Velluet** [Sarav-S/Laravel-Multiauth#18]
Hello,
Thank you for this great module!
I followed the installation instructions and by launching my program I got it: Class 'Illuminate\Auth\Guard' not found

/Users/xxx/Git/Alfred/vendor/sarav/laravel-multiauth/src/Guard.php
`    <?php
     
    namespace Sarav\Multiauth;
     
    use Illuminate\Support\Facades\Auth;
    use Illuminate\Auth\Guard as OriginalGuard;
    use Illuminate\Contracts\Auth\UserProvider;
    use Symfony\Component\HttpFoundation\Request;
    use Symfony\Component\HttpFoundation\Session\SessionInterface as SessionStore;
     
    class Guard extends OriginalGuard {
     
        protected $name;
        
        /**
         * Create a new authentication guard.
         *
         * @param  \Illuminate\Contracts\Auth\UserProvider  $provider
         * @param  \Symfony\Component\HttpFoundation\Session\SessionInterface  $session
         * @param  \Symfony\Component\HttpFoundation\Request  $request
         * @return void
         */
        public function __construct(UserProvider $provider, SessionStore $session, $name, Request $request = null)
        {
            $this->name = $name;
            parent::__construct($provider, $session, $request);
        }
     
        /**
         * Get a unique identifier for the auth session value.
         *
         * @return string
         */
        public function getName()
        {
            return 'login_' . $this->name . '_' . md5(get_class($this));
        }
     
        /**
         * Get the name of the cookie used to store the "recaller".

`

I am running PHP 7.2.7 and Laravel 5.8.14

**Comment by Sarav-S** [comment]
Hi Benjamin,

Thanks for trying out this package. As I can see, you are using Laravel 5.8, you can use Laravel's inbuilt authentication system to handle multiple authentication now. Please follow this article for more information

https://devmarketer.io/learn/setting-multi-authentication-laravel-5-4-part-1/
