### ISSUE TITLE
Support for LDAP ??

### ISSUE THREAD

**Issue by montes2012** [Sarav-S/Laravel-Multiauth#2]
Support for LDAP ??

auth.php

```
return ['multi' => [
    'user' => [
        'driver' => 'ldap',
        'model'  => App\User::class,
        'table'  => 'users'
    ],
    'admin' => [
        'driver' => 'eloquent',
        'model'  => App\Admin::class,
        'table'  => 'admins'
    ]
 ],
```

```
Route::get('user', function () {

    if(\Auth::attempt("user", ['email' => 'ohmq22@hotmail.com', 'password' => 'password']))
    {
        echo "ok!!";
    }else{

        echo "Noooo";
    }   

    return view('welcome');
});
```

Argument 1 passed to Sarav\Multiauth\Guard::__construct() must implement interface Illuminate\Contracts\Auth\UserProvider, instance of Illuminate\Auth\Guard given, called in /var/www/html/multi/vendor/sarav/laravel-multiauth/src/AuthManager.php on line 63 and defined

**Comment by Sarav-S** [comment]
Hi Montes,

No, it does not provide support for ldap. Same like laravel it supports only database and eloquent driver.

**Comment by montes2012** [comment]
Hi Sarav-S,

I authenticate with ldap https://github.com/SaschaDens/ldap-connector  but you have users in another table.

how could authenticate with both using Multiauth?
