### ISSUE TITLE
Every Auth::user() make a query

### ISSUE THREAD

**Issue by rydzyk** [Sarav-S/Laravel-Multiauth#3]
Hi

Every time I use Auth::user('admin') new query i made:

select \* from `admins` where `admins`.`id` = '6' limit 1

5xAuth::user('admin')  = 5 queries :(

I found that it should be saved in $this->user in Guard but it's not.

reg.
GM

**Comment by Sarav-S** [comment]
Thanks for reporting @rydzyk this has been fixed.

**Comment by rydzyk** [comment]
Thanks

I made little upgrade myself, from now on I keep user in session :)

GM
