### ISSUE TITLE
ErrorException in AuthManager.php Undefined variable: name

### ISSUE THREAD

**Issue by nickbr5** [Sarav-S/Laravel-Multiauth#4]
Hi, 

I installed your package but i keep getting the following error:

ErrorException in AuthManager.php line 120: Undefined variable: name

I don't understand what i'm doing wrong.
Any ideas?

thank you

**Comment by Sarav-S** [comment]
Hi,

Please try to pull in version 0.0.2 instead of version 0.0.1. It should work.

**Comment by nickbr5** [comment]
Hi, thanks!  that solved the issue, now i get this message:
Argument 1 passed to Illuminate\Auth\Guard::attempt() must be of the type array, string given
Looks like the string 'admin' is given to the attempt function of Guard instead of the array with credentials. Do i need to define another Guard class?

**Comment by Sarav-S** [comment]
Can you share your code? How do you attempt to login?

**Comment by Sarav-S** [comment]
Can you share your code? How do you attempt to login?

**Comment by nickbr5** [comment]
Got it working, if the string is not found in the multi config, it gives this error.
thanks anyway!

**Comment by Sarav-S** [comment]
Cool!
