### ISSUE TITLE
Cant config password_reset table

### ISSUE THREAD

**Issue by eleiva** [Sarav-S/Laravel-Multiauth#6]
Hi All!

I can't make work the password reset functionability for admins. 
As you may see below it attempts to delete a password reset row from an empty table (password_reset)

I always get:

```
SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: delete from `` where `email` = xxxx@gmail.com)
```

This is my configuration file

``` php
return [
  'multi' => [
    'user' => [
        'driver' => 'eloquent',
        'model'  => App\User::class,
        'table'  => 'users'
    ],
    'admin' => [ 
        'driver' => 'eloquent',
        'model'  => App\Admin::class,
        'table'  => 'admins',
        'password' => [
          'email' => 'emails.password',
          'table' => 'password_resets',
          'expire' => 60,
        ],
    ],
 ],
 ],
```

thanks in advance

**Comment by eleiva** [comment]
Ok i found what is happening:

This is my configuration now.

```
'password' => [
      'email' => 'emails.password',
      'table' => 'password_resets',
      'expire' => 60,
    ],
  'multi' => [
    'user' => [
        'driver' => 'eloquent',
        'model'  => App\User::class,
        'table'  => 'users'
    ],
    'admin' => [ 
        'driver' => 'eloquent',
        'model'  => App\Admin::class,
        'table'  => 'admins',
    ],
  ],
```

For now they will share the password_reset table between the two types of users.

Will be great to split them. Now i'm sharing templates too.

**Comment by funcoding** [comment]
@eleiva Why would you like to split password_reset table?

**Comment by Sarav-S** [comment]
@eleiva I really did not find a need to separate password_reset table. Email and password token will be unique for the table. So I thought separate table would be unnecessary here.
