### ISSUE TITLE
RedirectIfAuthenticated guest for user not working?

### ISSUE THREAD

**Issue by bartw2k9** [Sarav-S/Laravel-Multiauth#7]
if ($this->auth->check()) {
            return redirect('/home');
}

in class RedirectIfAuthenticated and AdminGuest not working? In what case it: \Auth::check('admin') returns true?

**Comment by Sarav-S** [comment]
@bwiatrni can you elaborate your issue little more?

**Comment by bartw2k9** [comment]
it was my mistake I have misunderstood how it works for route auth/login. It's true when you try call auth/login route again when you logged in. It's all right

**Comment by Sarav-S** [comment]
It happens :) No problem
