### ISSUE TITLE
One work, other not

### ISSUE THREAD

**Issue by xenkocz** [Sarav-S/Laravel-Multiauth#9]
Hello, I have a little problem, what should I do when the only work the first element and the second is ignored, so when I want for YouTuber account to log in and is specified as the first in a multi [...] and logs all right, but when used authority account, then it gets passes without errors, but Auth: user () not set
<code>

<pre>
return [
'multi' => [
    'authority' => [
        'driver' => 'eloquent',
        'model'  => \Inori\Authority::class, // Model Class
        'table'  => 'authority' //authority table
    ],
    'youtuber' => [
        'driver' => 'eloquent',
        'model'  => \Inori\Youtuber::class, // Model Class
        'table'  => 'youtuber' // youtuber table
    ]
 ],
 'password' => [
       'email' => 'emails.password',
       'table' => 'password_resets',
       'expire' => 60,
  ]
 ];
</pre>

</code>

Google translate ftw...

**Comment by Sarav-S** [comment]
Hi xenkocz,

You need to call user details with its parameter. For example, if you have logged in for authority, then retrieve the details by passing authority has its parameter. ie, Auth::user('authority'), Also for youtuber you will be calling Auth::user('youtuber')

Let me know if that works :)

**Comment by Sarav-S** [comment]
Hi xenkocz, did it work?

**Comment by xenkocz** [comment]
I dont know, I used a different library...

Merry Christmas

**Comment by Sarav-S** [comment]
Okay. 

Merry Christmas!
